config/routes.rb
Rails.application.routes.draw do
  resources :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    song = Song.new(song_params)
    if song.save
      redirect_to songs_path
    else
      flash[:errors] = song.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    @song.update(song_params)
    redirect_to @song
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist)
  end

  def set_song
    @song = Song.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>

  <%= f.label :artist %>
  <%= f.text_field :artist %> <br>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render 'form' %>

app/views/songs/index.html.erb
<h1>All Songs</h1>

<% @songs.each do |song| %>
  <%= link_to song.title, song %> 
  <%= link_to "Edit", edit_song_path(song) %>
  <%= link_to "Destroy", song_path(song), method: :delete, data: { confirm: "Are you sure?"} %>
  <br>
  <!-- <%#= link_to song.title, song_path(song) %> <br> -->
<% end %>

<%= link_to "New Song", new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<p><%= @song.artist %></p>